version: "3.9"
services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - EMBED_MODEL=${EMBED_MODEL}
      - CHROMA_DIR=/data/chroma
      - CHROMA_COLLECTION=ops_copilot
    volumes:
      - ./backend/chroma_data:/data/chroma
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
